; Collected rules from RFC 4647
; https://tools.ietf.org/html/rfc4647

language-range          = (1*8ALPHA *("-" 1*8alphanum)) / "*"

alphanum                = ALPHA / DIGIT

extended-language-range = (1*8ALPHA / "*")
                          *("-" (1*8alphanum / "*"))
