; Collected rules from RFC 7232
; https://tools.ietf.org/html/rfc7232

ETag = entity-tag

If-Match = "*" / ( *( "," OWS ) entity-tag *( OWS "," [ OWS entity-tag ] ) )

If-Modified-Since = HTTP-date

If-None-Match = "*" / ( *( "," OWS ) entity-tag *( OWS "," [ OWS entity-tag ] ) )

If-Unmodified-Since = HTTP-date

Last-Modified = HTTP-date

entity-tag = [ weak ] opaque-tag

etagc = "!" / %x23-7E / obs-text

opaque-tag = DQUOTE *etagc DQUOTE

weak = %x57.2F
