; Collected rules from RFC 7405
; https://tools.ietf.org/html/rfc7405

char-val =
    case-insensitive-string /
    case-sensitive-string

case-insensitive-string =
    [ "%i" ] quoted-string

case-sensitive-string =
    "%s" quoted-string

quoted-string  =
    DQUOTE *(%x20-21 / %x23-7E) DQUOTE
            ; quoted string of SP and VCHAR
            ;  without DQUOTE
