name: Make Check

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**.md"
      - "**.rst"
      - LICENSE
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.rst"
      - LICENSE

jobs:
  job:
    name: ${{ matrix.os }}-make-check
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip check')"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        compiler:
          - gcc
          - clang

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Dependencies
      run: sudo apt-get install -y valgrind
      if: "contains( matrix.os, 'ubuntu')"

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        export CC=${{ matrix.compiler }}
        cmake $GITHUB_WORKSPACE -DENABLE_VALGRIND=Off

    - name: Build Check
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --target check
